<a href="https://colab.research.google.com/github/Zizi32/k-nearest-neighbor-classifier/blob/main/KNN_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
from google.colab import files
import plotly.offline as plt
import plotly.graph_objs as go
from sklearn.datasets import make_moons
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

In [38]:
# Download Data
iris = load_iris()
X = iris.data[:, :3]
y = iris.target

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]]
[0 0 0]


In [47]:
for element in range(6,30):
    knn = KNeighborsClassifier(n_neighbors=element, weights='uniform')    
    knn.fit(X, y)

In [48]:
import plotly.graph_objs as go
from plotly.graph_objs import *
import plotly

Z = knn.predict(X)

trace = go.Scatter3d(x=X[:, 2], y=X[:, 1], z=X[:, 0], mode='markers',
    marker=dict(size=10,color=Z, colorscale='darkmint',showscale=False,line=Line(color='black',width=2),),)
graph_layout = go.Layout(
                scene=dict(
                  xaxis=dict(title='X-values'),
                  yaxis=dict(title='Y-values'),
                  zaxis=dict(title='Z-values')),
                  margin=dict(b=10, l=10, t=10))
data_graph = go.Figure(data=trace, layout=graph_layout)
data_graph.show(renderer='colab')

/usr/local/lib/python3.7/dist-packages/plotly/graph_objs/_deprecations.py:385: DeprecationWarning:

plotly.graph_objs.Line is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Line
  - plotly.graph_objs.layout.shape.Line
  - etc.


